import { useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { ArrowDownRight, ArrowUpRight, CalendarDays, ChevronLeft, Droplets, Edit3, FileText, HeartPulse, MapPin, Plus, ShieldAlert, UserRound } from 'lucide-react';
import { Link, useLocation, useParams } from 'wouter';
import { getGetPatientQueryKey, getListPatientLabsQueryKey, useCreatePatientLab, useGetPatient, useListPatientLabs, useUpdatePatient } from '@workspace/api-client-react';
import { FormField, Modal, PageIntro, SectionTitle, StateBlock, StatusBadge, ToastMessage, dateLabel } from '@/components/ui-kit';

export default function PatientDetail() {
  const params = useParams<{ id: string }>();
  const id = Number(params.id);
  const [, setLocation] = useLocation();
  const client = useQueryClient();
  const patientQuery = useGetPatient(id, { query: { enabled: Number.isFinite(id), queryKey: getGetPatientQueryKey(id) } });
  const labsQuery = useListPatientLabs(id, { query: { enabled: Number.isFinite(id), queryKey: getListPatientLabsQueryKey(id) } });
  const update = useUpdatePatient();
  const addLab = useCreatePatientLab();
  const [editOpen, setEditOpen] = useState(false);
  const [labOpen, setLabOpen] = useState(false);
  const [toast, setToast] = useState('');
  const patient = patientQuery.data;
  if (patientQuery.isLoading) return <StateBlock kind="loading" title="Loading patient profile" detail="Opening the latest care context." />;
  if (patientQuery.isError || !patient) return <StateBlock kind="error" title="Patient profile unavailable" detail="This record may have been removed or is temporarily unavailable." action={<Link href="/patients" data-testid="link-return-patients" className="rounded-lg bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">Return to registry</Link>} />;
  const labs = labsQuery.data ?? patient.labs ?? [];
  const latestLab = labs[0];
  const editSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const formData = new FormData(event.currentTarget);
    update.mutate({ id, data: { fullName: String(formData.get('fullName')), phone: String(formData.get('phone')), doctor: String(formData.get('doctor')), stage: String(formData.get('stage')), status: String(formData.get('status')) as 'stable' | 'watch' | 'critical', egfr: Number(formData.get('egfr')), address: String(formData.get('address')), diagnosis: String(formData.get('diagnosis')), allergies: String(formData.get('allergies')), medications: String(formData.get('medications')) } }, { onSuccess: () => { client.invalidateQueries({ queryKey: getGetPatientQueryKey(id) }); client.invalidateQueries({ queryKey: getListPatientLabsQueryKey(id) }); setEditOpen(false); setToast('Patient profile updated'); setTimeout(() => setToast(''), 3000); } });
  };
  const labSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const formData = new FormData(event.currentTarget);
    addLab.mutate({ id, data: { recordedAt: String(formData.get('recordedAt')), creatinine: Number(formData.get('creatinine')), egfr: Number(formData.get('egfr')), urea: Number(formData.get('urea')), potassium: Number(formData.get('potassium')), hemoglobin: Number(formData.get('hemoglobin')) } }, { onSuccess: () => { client.invalidateQueries({ queryKey: getListPatientLabsQueryKey(id) }); setLabOpen(false); setToast('Lab result added'); setTimeout(() => setToast(''), 3000); } });
  };
  return (
    <div className="page-enter">
      <button onClick={() => setLocation('/patients')} data-testid="button-back-patients" className="mb-5 inline-flex items-center gap-1 text-xs font-bold text-muted-foreground transition hover:text-primary"><ChevronLeft className="h-4 w-4" /> Danh sách bệnh nhân</button>
      <PageIntro eyebrow={`${patient.code} · patient profile`} title={patient.fullName} description={`${patient.stage} · Followed by ${patient.doctor}`} action={<button onClick={() => setEditOpen(true)} data-testid="button-edit-patient" className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-input bg-card px-4 text-sm font-bold transition hover:border-primary/40 hover:bg-secondary"><Edit3 className="h-4 w-4" /> Chỉnh sửa hồ sơ</button>} />
      <div className="grid gap-4 md:grid-cols-4">
        <div className="clinical-card rounded-xl p-4"><div className="eyebrow">Current status</div><div className="mt-3"><StatusBadge value={patient.status} /></div><p className="mt-2 text-xs text-muted-foreground">Updated {dateLabel(patient.updatedAt)}</p></div>
        <div className="clinical-card rounded-xl p-4"><div className="eyebrow">Kidney function</div><div className="mt-2 flex items-end gap-2"><span className="mono text-3xl font-bold">{patient.egfr}</span><span className="pb-1 text-xs text-muted-foreground">mL/min/1.73m²</span></div><div className={`mt-1 flex items-center gap-1 text-xs font-bold ${patient.egfrTrend === 'down' ? 'text-destructive' : 'text-primary'}`}>{patient.egfrTrend === 'down' ? <ArrowDownRight className="h-3.5 w-3.5" /> : <ArrowUpRight className="h-3.5 w-3.5" />} {patient.egfrTrend === 'down' ? 'Trending down' : patient.egfrTrend === 'up' ? 'Trending up' : 'Stable trend'}</div></div>
        <div className="clinical-card rounded-xl p-4"><div className="eyebrow">Next dialysis</div><div className="mt-3 flex items-center gap-2 text-sm font-bold"><CalendarDays className="h-4 w-4 text-primary" />{dateLabel(patient.nextDialysis, true)}</div><p className="mt-2 text-xs text-muted-foreground">Scheduled chair time</p></div>
        <div className="clinical-card rounded-xl p-4"><div className="eyebrow">Primary clinician</div><div className="mt-3 flex items-center gap-2 text-sm font-bold"><UserRound className="h-4 w-4 text-primary" />{patient.doctor}</div><p className="mt-2 text-xs text-muted-foreground">Nephrology care lead</p></div>
      </div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[.9fr_1.1fr]">
        <div className="space-y-6">
          <section className="clinical-card rounded-xl p-5 sm:p-6"><SectionTitle label="Patient context" title="Demographics & care plan" /><div className="grid gap-5 sm:grid-cols-2"><InfoItem icon={<UserRound />} label="Date of birth" value={`${dateLabel(patient.dateOfBirth)} · ${patient.gender}`} /><InfoItem icon={<MapPin />} label="Address" value={patient.address || 'Not recorded'} /><InfoItem icon={<HeartPulse />} label="Diagnosis" value={patient.diagnosis || 'Not recorded'} /><InfoItem icon={<ShieldAlert />} label="Allergies" value={patient.allergies || 'None recorded'} /></div><div className="mt-5 border-t border-border pt-4"><div className="eyebrow mb-2">Current medications</div><p className="text-sm leading-6 text-muted-foreground">{patient.medications || 'No medications recorded.'}</p></div></section>
          <section className="clinical-card rounded-xl p-5 sm:p-6"><SectionTitle label="Dialysis context" title="Treatment pathway" /><div className="flex items-start gap-3 rounded-lg bg-secondary/55 p-4"><div className="rounded-lg bg-card p-2 text-primary"><Droplets className="h-4 w-4" /></div><div><p className="text-sm font-bold">{patient.nextDialysis ? `Next session ${dateLabel(patient.nextDialysis, true)}` : 'No upcoming session'}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Review access notes and treatment tolerance before the next chair appointment.</p></div></div><Link href="/dialysis" data-testid="link-patient-dialysis" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-primary hover:underline">Open dialysis schedule <ChevronLeft className="h-3 w-3 rotate-180" /></Link></section>
        </div>
        <section className="clinical-card rounded-xl p-5 sm:p-6"><SectionTitle label="Longitudinal view" title="Lab history" action={<button onClick={() => setLabOpen(true)} data-testid="button-add-lab" className="inline-flex items-center gap-1.5 rounded-lg border border-input bg-card px-3 py-2 text-xs font-bold transition hover:border-primary/40 hover:bg-secondary"><Plus className="h-3.5 w-3.5" /> Add result</button>} />{labsQuery.isLoading ? <div className="py-8 text-center text-sm text-muted-foreground">Loading lab history…</div> : labs.length === 0 ? <div className="flex min-h-[240px] flex-col items-center justify-center text-center"><div className="rounded-full bg-secondary p-3 text-primary"><FileText className="h-5 w-5" /></div><p className="mt-3 text-sm font-bold">No lab results yet</p><p className="mt-1 text-xs text-muted-foreground">Add the first result to start the trend.</p></div> : <><div className="mb-5 grid grid-cols-3 gap-2">{[['eGFR', latestLab?.egfr, 'mL/min'], ['Creatinine', latestLab?.creatinine, 'mg/dL'], ['Potassium', latestLab?.potassium, 'mmol/L']].map(([label, value, unit]) => <div key={String(label)} className="rounded-lg bg-secondary/60 p-3"><div className="eyebrow !text-[10px]">{label}</div><div className="mono mt-2 text-lg font-bold">{value ?? '—'}</div><div className="mt-0.5 text-[10px] text-muted-foreground">{unit}</div></div>)}</div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left text-xs"><thead><tr className="border-b border-border text-[10px] uppercase tracking-[.1em] text-muted-foreground"><th className="pb-3 font-bold">Recorded</th><th className="pb-3 font-bold">eGFR</th><th className="pb-3 font-bold">Creatinine</th><th className="pb-3 font-bold">Urea</th><th className="pb-3 font-bold">K+</th><th className="pb-3 font-bold">Hgb</th></tr></thead><tbody className="divide-y divide-border">{labs.map((lab) => <tr key={lab.id} data-testid={`row-lab-${lab.id}`}><td className="py-3 font-semibold">{dateLabel(lab.recordedAt)}</td><td className="mono py-3 font-bold">{lab.egfr}</td><td className="mono py-3">{lab.creatinine}</td><td className="mono py-3">{lab.urea}</td><td className="mono py-3">{lab.potassium}</td><td className="mono py-3">{lab.hemoglobin}</td></tr>)}</tbody></table></div></>}</section>
      </div>
      <Modal open={editOpen} onClose={() => setEditOpen(false)} title="Edit patient profile" description="Update the care team fields that have changed.">
        <form onSubmit={editSubmit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><FormField label="Full name"><input name="fullName" required defaultValue={patient.fullName} className="form-input" /></FormField><FormField label="Phone"><input name="phone" required defaultValue={patient.phone} className="form-input" /></FormField></div><div className="grid gap-4 sm:grid-cols-3"><FormField label="Stage"><input name="stage" required defaultValue={patient.stage} className="form-input" /></FormField><FormField label="eGFR"><input name="egfr" required type="number" defaultValue={patient.egfr} className="form-input" /></FormField><FormField label="Status"><select name="status" defaultValue={patient.status} className="form-input"><option value="stable">Stable</option><option value="watch">Watch</option><option value="critical">Critical</option></select></FormField></div><div className="grid gap-4 sm:grid-cols-2"><FormField label="Doctor"><input name="doctor" required defaultValue={patient.doctor} className="form-input" /></FormField><FormField label="Address"><input name="address" defaultValue={patient.address} className="form-input" /></FormField></div><div className="grid gap-4 sm:grid-cols-2"><FormField label="Diagnosis"><input name="diagnosis" defaultValue={patient.diagnosis} className="form-input" /></FormField><FormField label="Allergies"><input name="allergies" defaultValue={patient.allergies} className="form-input" /></FormField></div><FormField label="Medications"><textarea name="medications" defaultValue={patient.medications} className="form-input min-h-20 resize-y" /></FormField><div className="flex justify-end gap-2 border-t border-border pt-5"><button type="button" onClick={() => setEditOpen(false)} data-testid="button-cancel-edit" className="rounded-lg px-4 py-2.5 text-sm font-bold text-muted-foreground hover:bg-muted">Cancel</button><button disabled={update.isPending} data-testid="button-submit-edit" className="rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">{update.isPending ? 'Updating…' : 'Update profile'}</button></div></form>
      </Modal>
      <Modal open={labOpen} onClose={() => setLabOpen(false)} title="Add lab result" description="Record a new renal panel for this patient.">
        <form onSubmit={labSubmit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><FormField label="Recorded at"><input required name="recordedAt" type="date" defaultValue={new Date().toISOString().slice(0, 10)} className="form-input" /></FormField><FormField label="eGFR"><input required name="egfr" type="number" step="0.1" className="form-input" /></FormField></div><div className="grid grid-cols-2 gap-4"><FormField label="Creatinine"><input required name="creatinine" type="number" step="0.01" className="form-input" /></FormField><FormField label="Urea"><input required name="urea" type="number" step="0.1" className="form-input" /></FormField><FormField label="Potassium"><input required name="potassium" type="number" step="0.1" className="form-input" /></FormField><FormField label="Hemoglobin"><input required name="hemoglobin" type="number" step="0.1" className="form-input" /></FormField></div><div className="flex justify-end gap-2 border-t border-border pt-5"><button type="button" onClick={() => setLabOpen(false)} data-testid="button-cancel-lab" className="rounded-lg px-4 py-2.5 text-sm font-bold text-muted-foreground hover:bg-muted">Cancel</button><button disabled={addLab.isPending} data-testid="button-submit-lab" className="rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">{addLab.isPending ? 'Saving…' : 'Add lab result'}</button></div></form>
      </Modal>
      {toast && <ToastMessage message={toast} />}
    </div>
  );
}

function InfoItem({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return <div className="flex gap-2.5"><span className="mt-0.5 text-primary [&>svg]:h-4 [&>svg]:w-4">{icon}</span><div><div className="eyebrow !text-[10px]">{label}</div><p className="mt-1 text-sm font-semibold leading-5">{value}</p></div></div>;
}